[package]
name = "cryptopals"
version = "0.0.0"
authors = ["Mack Stump <mack@mackstump.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
data-encoding = "2.3.0"
openssl = "0.10.30"
