[package]
name = "challenges"
version = "0.1.0"
authors = ["Mack Stump <mack@mackstump.com>"]
edition = "2018"

[dependencies]
base64 = "0.13.0"
console = "0.12.0"
indicatif = "0.15.0"
log = "0.4.11"
rand = "0.7.3"
simple_logger = "1.9.0"
rayon = "1.4.1"

cryptopals = { path = ".." }
